# Travis specific docker-compose to handle database and server dependencies
omp-express-mongo-api:
    build: .
    working_dir: /omp
    volumes:
        - ./package.json:/omp/package.json:rw
        - ./server.js:/omp/server.js:rw
        - ./routes/:/omp/routes/:rw
        - ./dao/:/omp/dao/:rw
    environment:
        NODE_ENV: development
        NODE_PATH: /usr/local/lib/node_modules/omp-express-mongo-api/node_modules/
    ports:
        - "8001:8001"
    links:
        - omp-mongo
    command: npm start

omp-mongo:
    image: mongo
    command: --smallfiles
    expose:
        - "27017"
