sudo: required

language: node_js
node_js:
    - node

services:
    - docker

branches:
    except:
        - gh-pages

before_script:
    - docker-compose -f .travis-docker-compose.yml build
    - docker-compose -f .travis-docker-compose.yml up -d
    - npm install --only=dev

script:
    - docker ps | grep omp-express-mongo-api
    - docker ps | grep omp-mongo
    - npm test

after_script:
    - docker-compose -f .travis.docker-compose.yml stop
